# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conversor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Conversor(object):
    def setupUi(self, Conversor):
        Conversor.setObjectName("Conversor")
        Conversor.resize(457, 413)
        self.centralwidget = QtWidgets.QWidget(Conversor)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_converter = QtWidgets.QPushButton(self.centralwidget)
        self.botao_converter.setGeometry(QtCore.QRect(90, 290, 75, 23))
        self.botao_converter.setObjectName("botao_converter")
        self.botao_sair = QtWidgets.QPushButton(self.centralwidget)
        self.botao_sair.setGeometry(QtCore.QRect(300, 290, 75, 23))
        self.botao_sair.setObjectName("botao_sair")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 60, 361, 16))
        self.label.setObjectName("label")
        self.entrada_temp = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_temp.setGeometry(QtCore.QRect(210, 100, 113, 20))
        self.entrada_temp.setObjectName("entrada_temp")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 91, 16))
        self.label_2.setObjectName("label_2")
        Conversor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Conversor)
        self.statusbar.setObjectName("statusbar")
        Conversor.setStatusBar(self.statusbar)




        self.retranslateUi(Conversor)
        self.botao_sair.clicked.connect(Conversor.close)
        QtCore.QMetaObject.connectSlotsByName(Conversor)
        self.botao_converter.clicked.connect(self.converte)

    def converte(self):
        temp = int(self.entrada_temp.text())
        temp = (temp - 32) * 5 / 9

        msg = QtWidgets.QMessageBox()
        msg.setIcon(msg.Information)
        msg.setWindowTitle('Sucesso')
        msg.setText('Resultado:' + str(temp) + '°c')
        msg.exec()

    def retranslateUi(self, Conversor):
        _translate = QtCore.QCoreApplication.translate
        Conversor.setWindowTitle(_translate("Conversor", "Conversor F/C - versão 1"))
        self.botao_converter.setText(_translate("Conversor", "Converter"))
        self.botao_sair.setText(_translate("Conversor", "Sair"))
        self.label.setText(_translate("Conversor", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ff0000;\">Conversor de temperatura de Fahrenheint(\'f\') para Celcius ( \'c\')</span></p></body></html>"))
        self.label_2.setText(_translate("Conversor", "Temperatura:"))


if __name__ =='__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui=Ui_Conversor()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec())
