# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GeradordeMensagem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_GeradordeMensagem(object):
    def setupUi(self, GeradordeMensagem):
        GeradordeMensagem.setObjectName("GeradordeMensagem")
        GeradordeMensagem.resize(468, 383)
        self.centralwidget = QtWidgets.QWidget(GeradordeMensagem)
        self.centralwidget.setObjectName("centralwidget")
        self.Sair_button = QtWidgets.QPushButton(self.centralwidget)
        self.Sair_button.setGeometry(QtCore.QRect(280, 270, 75, 23))
        self.Sair_button.setObjectName("Sair_button")
        self.gerador_button = QtWidgets.QPushButton(self.centralwidget)
        self.gerador_button.setGeometry(QtCore.QRect(80, 270, 101, 23))
        self.gerador_button.setObjectName("gerador_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 70, 381, 20))
        self.label.setObjectName("label")
        GeradordeMensagem.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GeradordeMensagem)
        self.statusbar.setObjectName("statusbar")
        GeradordeMensagem.setStatusBar(self.statusbar)

        self.retranslateUi(GeradordeMensagem)
        self.Sair_button.clicked.connect(GeradordeMensagem.close)
        QtCore.QMetaObject.connectSlotsByName(GeradordeMensagem)
        self.gerador_button.clicked.connect(self.GerarMensagem)

    def GerarMensagem(self):
        import random
        msg1='Boa noite'
        msg2='Ola Galerinha'
        msg3='Bom dia, Me dar um 100 ai  professor kkkkkkkk'
        lista= [msg1,msg2,msg3]
        msgAleatoria=random.choice(lista)

        msg = QtWidgets.QMessageBox()
        msg.setIcon(msg.Information)
        msg.setWindowTitle('Sucesso')
        msg.setText(str(msgAleatoria))
        msg.exec()

    def retranslateUi(self, GeradordeMensagem):
        _translate = QtCore.QCoreApplication.translate
        GeradordeMensagem.setWindowTitle(_translate("GeradordeMensagem", "Gerador de Mensagem de bom dia"))
        self.Sair_button.setText(_translate("GeradordeMensagem", "Sair"))
        self.gerador_button.setText(_translate("GeradordeMensagem", "Gerar Mensagem"))
        self.label.setText(_translate("GeradordeMensagem", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Gerador de Mensagem de Bom Dia Aleatorio</span></p></body></html>"))

if __name__ =='__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui=Ui_GeradordeMensagem()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec())